### ISSUE TITLE
Multiple elements

### ISSUE THREAD

**Issue by richgcook** [ariona/hover3d#2]
Is it possible to get this working out the box with multiple elements without multiple instances? It seems that when called, on hover of one element, it applies the hover to all elements at the same time.

**Comment by ariona** [comment]
Yeah it's possible, just use class as a selector.

**Comment by richgcook** [comment]
@ariona Thanks for the reply. I did just that but seems to trigger them all on hover?

**Comment by richgcook** [comment]
@ariona See here: http://codepen.io/anon/pen/gLzmOW

**Comment by ariona** [comment]
@richgcook see here https://jsfiddle.net/dagsr1rq/

**Comment by richgcook** [comment]
Ah! I see where I've gone wrong. Thanks.
