### ISSUE TITLE
Full screen visibility on a 5k imac

### ISSUE THREAD

**Issue by stefanreimert** [ariona/hover3d#6]
I am having the problem when i add the shine to the banner.
When i hover this a couple of times it giving me stripes on my screen.

I have the latest version of "hover3d".
In the attachment is a screenshot of how it looks.

The pink squire is the point where it breaks.

![schermafbeelding 2017-02-20 om 14 21 58](https://cloud.githubusercontent.com/assets/4490250/23126869/071ca786-f779-11e6-8672-b845b27a9c22.jpeg)

**Comment by ariona** [comment]
Can't reproduce this problem, can you create a pen on codepen.io .  The flickering effect usually comes from overlapping element in 3d space.

**Comment by stefanreimert** [comment]
Thank you for this one i was checkout out my css and did something with the translate on the shine class. So was my bad but thank you for the reply.

**Comment by ariona** [comment]
great, thats good to know 👍
