### ISSUE TITLE
Odd behavior in Safari

### ISSUE THREAD

**Issue by anoveskey** [ariona/hover3d#7]
This plugin is great! Definitely makes the screen pop. However, I've noticed some odd behavior in Safari. It seems project__cards are being overlayed by the element used to create the shine effect. 

![screen shot 2017-07-13 at 9 30 40 am](https://user-images.githubusercontent.com/5287502/28168876-86f40c2e-67ae-11e7-9942-b6821f0f4899.png)

**Comment by ariona** [comment]
Well. that's weird. i haven't encountered that issue on my safari. which version you're using?.
Or just turn it off by setting shine to false

**Comment by anoveskey** [comment]
I figured out the problem. Apparently the javascript that assigns the css 'transform-style: preserve-3d' rule was conflicting with another css rule I had in place. I solved the problem by adding:

transform-style: flat !important;

to the "project" class using the selector ".project[style]"
